const recipes = {
    breakfast: [
        { name: 'Poha', ingredients: ['flattened rice', 'onion', 'potato', 'mustard seeds'], preparation: ['Soak flattened rice, sauté with onions, potatoes, and spices.'] },
        { name: 'Aloo Paratha', ingredients: ['potato', 'wheat flour', 'spices'], preparation: ['Stuff dough with spiced potatoes and cook on a griddle.'] },
        { name: 'Masala Dosa', ingredients: ['rice', 'urad dal', 'potato', 'onion'], preparation: ['Make dosa batter, cook with potato filling.'] },
        { name: 'Idli', ingredients: ['rice', 'urad dal', 'salt'], preparation: ['Steam fermented batter in molds.'] },
        { name: 'Upma', ingredients: ['semolina', 'vegetables', 'mustard seeds'], preparation: ['Cook semolina with vegetables and spices.'] },
        { name: 'Puri Bhaji', ingredients: ['wheat flour', 'potato', 'spices'], preparation: ['Make puris and serve with spiced potato bhaji.'] },
        { name: 'Chole Bhature', ingredients: ['chickpeas', 'flour', 'spices'], preparation: ['Serve spiced chickpeas with fried bread.'] },
        { name: 'Dhokla', ingredients: ['gram flour', 'yogurt', 'spices'], preparation: ['Steam fermented batter and cut into pieces.'] },
        { name: 'Thepla', ingredients: ['wheat flour', 'fenugreek leaves', 'spices'], preparation: ['Make dough with spices, cook on griddle.'] },
        { name: 'Methi Paratha', ingredients: ['wheat flour', 'fenugreek leaves', 'spices'], preparation: ['Combine ingredients, roll into parathas, cook on griddle.'] },
        { name: 'Uttapam', ingredients: ['rice', 'urad dal', 'onion', 'tomato'], preparation: ['Cook batter with vegetables on griddle.'] },
        { name: 'Pesarattu', ingredients: ['green gram', 'onion', 'ginger'], preparation: ['Make dosa from green gram batter with onions.'] },
        { name: 'Pongal', ingredients: ['rice', 'moong dal', 'peppercorns'], preparation: ['Cook rice and dal with spices.'] },
        { name: 'Sabudana Khichdi', ingredients: ['tapioca pearls', 'peanuts', 'potato'], preparation: ['Cook soaked pearls with peanuts and potatoes.'] },
        { name: 'Vada', ingredients: ['urad dal', 'spices'], preparation: ['Fry ground dal batter into fritters.'] },
        { name: 'Matar Kachori', ingredients: ['flour', 'peas', 'spices'], preparation: ['Fill dough with spiced peas and fry.'] },
        { name: 'Besan Chilla', ingredients: ['gram flour', 'spices', 'vegetables'], preparation: ['Cook batter with veggies on griddle.'] },
        { name: 'Bread Pakora', ingredients: ['bread', 'gram flour', 'spices'], preparation: ['Batter bread slices with gram flour and fry.'] },
        { name: 'Rava Idli', ingredients: ['semolina', 'yogurt', 'spices'], preparation: ['Steam batter in idli molds.'] },
        { name: 'Moong Dal Chilla', ingredients: ['moong dal', 'spices'], preparation: ['Cook ground dal batter on a griddle.'] }
    ],
    mainDishes: [
        { name: 'Butter Chicken', ingredients: ['chicken', 'butter', 'tomato', 'cream'], preparation: ['Cook chicken in creamy tomato sauce.'] },
        { name: 'Biryani', ingredients: ['rice', 'chicken', 'spices', 'yogurt'], preparation: ['Layer marinated chicken with rice and cook.'] },
        { name: 'Paneer Butter Masala', ingredients: ['paneer', 'tomato', 'cream', 'spices'], preparation: ['Cook paneer in creamy tomato sauce.'] },
        { name: 'Chole', ingredients: ['chickpeas', 'tomato', 'onion', 'spices'], preparation: ['Cook chickpeas with spiced gravy.'] },
        { name: 'Dal Makhani', ingredients: ['urad dal', 'kidney beans', 'cream'], preparation: ['Simmer dal and beans with spices and cream.'] },
        { name: 'Palak Paneer', ingredients: ['paneer', 'spinach', 'spices'], preparation: ['Cook paneer in pureed spinach.'] },
        { name: 'Rajma', ingredients: ['kidney beans', 'tomato', 'spices'], preparation: ['Simmer beans with spiced gravy.'] },
        { name: 'Aloo Gobi', ingredients: ['potato', 'cauliflower', 'spices'], preparation: ['Cook potato and cauliflower with spices.'] },
        { name: 'Mutton Curry', ingredients: ['mutton', 'spices', 'yogurt'], preparation: ['Cook mutton in a spiced gravy.'] },
        { name: 'Fish Curry', ingredients: ['fish', 'coconut', 'spices'], preparation: ['Cook fish in a spiced coconut gravy.'] },
        { name: 'Baingan Bharta', ingredients: ['eggplant', 'tomato', 'onion'], preparation: ['Roast eggplant and cook with spices.'] },
        { name: 'Kadhi Pakora', ingredients: ['gram flour', 'yogurt', 'spices'], preparation: ['Cook gram flour dumplings in spiced yogurt.'] },
        { name: 'Malai Kofta', ingredients: ['paneer', 'potato', 'cream'], preparation: ['Cook paneer and potato balls in creamy gravy.'] },
        { name: 'Vegetable Korma', ingredients: ['mixed vegetables', 'coconut', 'spices'], preparation: ['Cook vegetables in a spiced coconut sauce.'] },
        { name: 'Chicken Tikka Masala', ingredients: ['chicken', 'tomato', 'cream', 'spices'], preparation: ['Cook marinated chicken in spiced sauce.'] },
        { name: 'Lamb Vindaloo', ingredients: ['lamb', 'vinegar', 'spices'], preparation: ['Cook lamb with vinegar and spices.'] },
        { name: 'Kofta Curry', ingredients: ['meatballs', 'spices', 'gravy'], preparation: ['Cook meatballs in spiced gravy.'] },
        { name: 'Bhindi Masala', ingredients: ['okra', 'onion', 'spices'], preparation: ['Cook okra with spices and onion.'] },
        { name: 'Jeera Aloo', ingredients: ['potato', 'cumin', 'spices'], preparation: ['Cook potato with cumin and spices.'] },
        { name: 'Egg Curry', ingredients: ['eggs', 'tomato', 'spices'], preparation: ['Cook boiled eggs in spiced gravy.'] }
    ],
    beverages: [
        { name: 'Masala Chai', ingredients: ['tea leaves', 'milk', 'spices', 'sugar'], preparation: ['Simmer tea with milk, spices, and sugar.'] },
        { name: 'Mango Lassi', ingredients: ['mango', 'yogurt', 'sugar', 'milk'], preparation: ['Blend mango with yogurt and sugar.'] },
        { name: 'Nimbu Pani', ingredients: ['lemon', 'water', 'sugar', 'salt'], preparation: ['Mix lemon juice with water, sugar, and salt.'] },
        { name: 'Thandai', ingredients: ['milk', 'almonds', 'spices', 'sugar'], preparation: ['Blend milk with almonds, spices, and sugar.'] },
        { name: 'Jaljeera', ingredients: ['cumin', 'mint', 'lemon'], preparation: ['Mix cumin, mint, and lemon with water.'] },
        { name: 'Aam Panna', ingredients: ['raw mango', 'mint', 'cumin'], preparation: ['Blend mango with mint and cumin.'] },
        { name: 'Falooda', ingredients: ['milk', 'rose syrup', 'vermicelli'], preparation: ['Layer milk with syrup and vermicelli.'] },
        { name: 'Badam Milk', ingredients: ['almonds', 'milk', 'sugar'], preparation: ['Blend almonds with milk and sugar.'] },
        { name: 'Coconut Water', ingredients: ['coconut water'], preparation: ['Serve chilled.'] },
        { name: 'Sugarcane Juice', ingredients: ['sugarcane'], preparation: ['Extract juice and serve chilled.'] },
        { name: 'Masala Buttermilk', ingredients: ['buttermilk', 'cumin', 'mint'], preparation: ['Mix buttermilk with cumin and mint.'] },
        { name: 'Ginger Lemon Tea', ingredients: ['ginger', 'lemon', 'tea'], preparation: ['Boil ginger with tea and lemon.'] },
        { name: 'Rose Milk', ingredients: ['milk', 'rose syrup'], preparation: ['Mix milk with rose syrup.'] },
        { name: 'Kesar Pista Lassi', ingredients: ['yogurt', 'saffron', 'pistachios'], preparation: ['Blend yogurt with saffron and pistachios.'] },
        { name: 'Mint Lassi', ingredients: ['yogurt', 'mint', 'salt'], preparation: ['Blend yogurt with mint and salt.'] },
        { name: 'Pineapple Juice', ingredients: ['pineapple'], preparation: ['Juice the pineapple.'] },
        { name: 'Carrot Kanji', ingredients: ['carrot', 'mustard seeds', 'water'], preparation: ['Ferment carrots with mustard.'] },
        { name: 'Bael Sharbat', ingredients: ['bael fruit', 'water'], preparation: ['Mix bael pulp with water.'] },
        { name: 'Kokum Sherbet', ingredients: ['kokum', 'sugar', 'cumin'], preparation: ['Blend kokum with sugar and cumin.'] },
        { name: 'Apple Cider', ingredients: ['apple', 'cinnamon'], preparation: ['Boil apples with cinnamon and strain.'] }
    ],
    snacks: [
        { name: 'Pani Puri', ingredients: ['puri', 'potato', 'tamarind water'], preparation: ['Fill puris with potato and tamarind water.'] },
        { name: 'Bhel Puri', ingredients: ['puffed rice', 'sev', 'chutneys'], preparation: ['Mix ingredients and serve.'] },
        { name: 'Aloo Chaat', ingredients: ['potato', 'chutney', 'spices'], preparation: ['Toss fried potatoes with chutney and spices.'] },
        { name: 'Sev Puri', ingredients: ['puri', 'potato', 'chutneys'], preparation: ['Top puris with potatoes and chutneys.'] },
        { name: 'Chana Jor Garam', ingredients: ['black gram', 'spices'], preparation: ['Mix roasted gram with spices.'] },
        { name: 'Dahi Vada', ingredients: ['lentils', 'yogurt', 'chutneys'], preparation: ['Serve fried vada in yogurt with chutneys.'] },
        { name: 'Kachori', ingredients: ['flour', 'spices'], preparation: ['Fill dough with spiced mixture and fry.'] },
        { name: 'Aloo Bonda', ingredients: ['potato', 'gram flour'], preparation: ['Batter potato balls and fry.'] },
        { name: 'Pakora', ingredients: ['vegetables', 'gram flour'], preparation: ['Batter vegetables and fry.'] },
        { name: 'Bread Roll', ingredients: ['bread', 'potato', 'spices'], preparation: ['Fill bread with potato, roll, and fry.'] },
        { name: 'Vada Pav', ingredients: ['bun', 'potato fritter', 'chutneys'], preparation: ['Serve fritter in bun with chutney.'] },
        { name: 'Mirchi Bajji', ingredients: ['chili', 'gram flour'], preparation: ['Batter chili peppers and fry.'] },
        { name: 'Murmura', ingredients: ['puffed rice', 'spices'], preparation: ['Mix puffed rice with spices.'] },
        { name: 'Samosa Chaat', ingredients: ['samosa', 'yogurt', 'chutneys'], preparation: ['Top samosa with yogurt and chutneys.'] },
        { name: 'Bhakarwadi', ingredients: ['flour', 'spices'], preparation: ['Roll spiced dough, slice, and fry.'] },
        { name: 'Papdi Chaat', ingredients: ['papdi', 'potato', 'yogurt', 'chutneys'], preparation: ['Top papdi with potato, yogurt, and chutneys.'] },
        { name: 'Chakli', ingredients: ['rice flour', 'spices'], preparation: ['Shape spiced dough and fry.'] },
        { name: 'Mathri', ingredients: ['flour', 'spices'], preparation: ['Shape spiced dough and fry.'] },
        { name: 'Methi Na Gota', ingredients: ['fenugreek', 'gram flour'], preparation: ['Batter fenugreek leaves and fry.'] },
        { name: 'Dhokla Sandwich', ingredients: ['gram flour', 'spices'], preparation: ['Layer dhokla with chutney.'] }
    ],
    soups: [
        { name: 'Tomato Shorba', ingredients: ['tomato', 'spices', 'broth'], preparation: ['Cook tomatoes with spices and blend.'] },
        { name: 'Mulligatawny Soup', ingredients: ['lentils', 'chicken', 'curry powder'], preparation: ['Cook lentils and chicken with spices, blend and serve.'] },
        { name: 'Dal Shorba', ingredients: ['lentils', 'spices', 'onion'], preparation: ['Cook lentils with spices, blend and serve.'] },
        { name: 'Palak Soup', ingredients: ['spinach', 'spices', 'cream'], preparation: ['Cook spinach with spices, blend and add cream.'] },
        { name: 'Vegetable Soup', ingredients: ['mixed vegetables', 'spices', 'broth'], preparation: ['Cook veggies with broth and spices.'] },
        { name: 'Lemon Coriander Soup', ingredients: ['lemon', 'coriander', 'broth'], preparation: ['Simmer broth with coriander and lemon.'] },
        { name: 'Chicken Shorba', ingredients: ['chicken', 'spices', 'broth'], preparation: ['Simmer chicken in spices and broth.'] },
        { name: 'Mushroom Soup', ingredients: ['mushroom', 'cream', 'broth'], preparation: ['Cook mushrooms with broth, blend, add cream.'] },
        { name: 'Pumpkin Soup', ingredients: ['pumpkin', 'spices', 'cream'], preparation: ['Cook pumpkin with spices, blend and add cream.'] },
        { name: 'Sweet Corn Soup', ingredients: ['corn', 'vegetables', 'broth'], preparation: ['Simmer corn and veggies in broth.'] },
        { name: 'Rasam', ingredients: ['tomato', 'spices', 'tamarind'], preparation: ['Simmer tomatoes with spices and tamarind.'] },
        { name: 'Hot and Sour Soup', ingredients: ['vegetables', 'vinegar', 'spices'], preparation: ['Cook vegetables with vinegar and spices.'] },
        { name: 'Dal Palak Soup', ingredients: ['lentils', 'spinach', 'spices'], preparation: ['Cook lentils with spinach and spices.'] },
        { name: 'Carrot Soup', ingredients: ['carrot', 'ginger', 'cream'], preparation: ['Cook carrots with ginger, blend, and add cream.'] },
        { name: 'Coconut Milk Soup', ingredients: ['coconut milk', 'vegetables', 'spices'], preparation: ['Simmer coconut milk with vegetables.'] },
        { name: 'Tamatar Dhaniya Shorba', ingredients: ['tomato', 'coriander', 'spices'], preparation: ['Simmer tomatoes with coriander and spices.'] },
        { name: 'Beetroot Soup', ingredients: ['beetroot', 'spices', 'cream'], preparation: ['Cook beetroot with spices, blend, and add cream.'] },
        { name: 'Ginger Soup', ingredients: ['ginger', 'spices', 'broth'], preparation: ['Simmer ginger in broth with spices.'] },
        { name: 'Mutton Yakhni', ingredients: ['mutton', 'yogurt', 'spices'], preparation: ['Simmer mutton in yogurt-based broth with spices.'] },
        { name: 'Spicy Lentil Soup', ingredients: ['lentils', 'spices', 'broth'], preparation: ['Cook lentils with spices and blend.'] }
    ],
    appetizers: [
        { name: 'Samosa', ingredients: ['potatoes', 'peas', 'flour', 'spices'], preparation: ['Make dough, fill with spiced potatoes and peas, shape, and fry.'] },
        { name: 'Paneer Tikka', ingredients: ['paneer', 'yogurt', 'spices', 'bell peppers'], preparation: ['Marinate paneer and veggies, then grill or bake.'] },
        { name: 'Aloo Tikki', ingredients: ['potatoes', 'peas', 'spices', 'breadcrumbs'], preparation: ['Shape spiced potato mixture into patties, coat with breadcrumbs, and fry.'] },
        { name: 'Hara Bhara Kabab', ingredients: ['spinach', 'peas', 'potato', 'spices'], preparation: ['Combine ingredients, shape into patties, and fry.'] },
        { name: 'Dahi Puri', ingredients: ['puri', 'potato', 'yogurt', 'spices'], preparation: ['Fill puris with spiced potatoes, yogurt, and tamarind chutney.'] },
        { name: 'Prawn Koliwada', ingredients: ['prawns', 'flour', 'spices'], preparation: ['Batter prawns with spices and fry.'] },
        { name: 'Onion Pakora', ingredients: ['onion', 'gram flour', 'spices'], preparation: ['Batter onion slices and fry.'] },
        { name: 'Chicken Pakora', ingredients: ['chicken', 'gram flour', 'spices'], preparation: ['Batter chicken pieces and fry.'] },
        { name: 'Rajma Galouti', ingredients: ['rajma', 'spices', 'breadcrumbs'], preparation: ['Mash rajma with spices, shape into patties, and fry.'] },
        { name: 'Palak Chaat', ingredients: ['spinach', 'yogurt', 'spices'], preparation: ['Fry spinach and serve with yogurt and chutneys.'] },
        { name: 'Mushroom Tikka', ingredients: ['mushroom', 'yogurt', 'spices'], preparation: ['Marinate mushrooms with spices and grill.'] },
        { name: 'Chicken Seekh Kebab', ingredients: ['chicken', 'spices'], preparation: ['Shape minced chicken onto skewers and grill.'] },
        { name: 'Fish Amritsari', ingredients: ['fish', 'gram flour', 'spices'], preparation: ['Batter fish with spices and fry.'] },
        { name: 'Vegetable Spring Rolls', ingredients: ['vegetables', 'spring roll wrappers', 'spices'], preparation: ['Fill wrappers with vegetables and fry.'] },
        { name: 'Mutton Shami Kebab', ingredients: ['mutton', 'lentils', 'spices'], preparation: ['Shape mutton and lentils into patties and fry.'] },
        { name: 'Dhokla', ingredients: ['gram flour', 'yogurt', 'spices'], preparation: ['Steam fermented batter, cut into pieces.'] },
        { name: 'Stuffed Mushroom', ingredients: ['mushrooms', 'cheese', 'spices'], preparation: ['Stuff mushrooms with spiced cheese mixture and bake.'] },
        { name: 'Achari Paneer Tikka', ingredients: ['paneer', 'pickle spices', 'yogurt'], preparation: ['Marinate paneer with spices and grill.'] },
        { name: 'Pav Bhaji', ingredients: ['vegetables', 'spices', 'bread'], preparation: ['Cook spiced vegetables and serve with bread.'] },
        { name: 'Methi Malai Chicken Tikka', ingredients: ['chicken', 'methi', 'cream'], preparation: ['Marinate chicken in methi and cream, then grill.'] }
    ],
    salads: [
        { name: 'Kachumber Salad', ingredients: ['cucumber', 'tomato', 'onion', 'lemon'], preparation: ['Chop vegetables, mix with lemon juice and spices.'] },
        { name: 'Sprouted Moong Salad', ingredients: ['sprouted moong', 'tomato', 'cucumber', 'lemon'], preparation: ['Mix sprouts with veggies and lemon juice.'] },
        { name: 'Paneer Salad', ingredients: ['paneer', 'capsicum', 'onion', 'tomato'], preparation: ['Grill paneer and mix with vegetables.'] },
        { name: 'Mango Salad', ingredients: ['raw mango', 'onion', 'mint'], preparation: ['Mix mango with onions, mint, and spices.'] },
        { name: 'Fruit Chaat', ingredients: ['apple', 'banana', 'grapes', 'orange'], preparation: ['Mix chopped fruits with chaat masala.'] },
        { name: 'Carrot and Cucumber Salad', ingredients: ['carrot', 'cucumber', 'lemon'], preparation: ['Mix grated carrot and cucumber with lemon juice.'] },
        { name: 'Beetroot Salad', ingredients: ['beetroot', 'cucumber', 'tomato'], preparation: ['Mix beetroot with cucumber and tomato.'] },
        { name: 'Palak Chaat', ingredients: ['spinach', 'yogurt', 'tamarind'], preparation: ['Fry spinach leaves, top with yogurt and tamarind chutney.'] },
        { name: 'Chana Salad', ingredients: ['chickpeas', 'onion', 'tomato'], preparation: ['Mix chickpeas with onions, tomatoes, and spices.'] },
        { name: 'Aloo Chaat', ingredients: ['potatoes', 'spices', 'lemon'], preparation: ['Fry potatoes and toss with spices and lemon.'] },
        { name: 'Corn Salad', ingredients: ['corn', 'capsicum', 'tomato'], preparation: ['Mix corn with vegetables and spices.'] },
        { name: 'Rajma Salad', ingredients: ['kidney beans', 'onion', 'tomato'], preparation: ['Mix kidney beans with veggies and spices.'] },
        { name: 'Pomegranate Raita', ingredients: ['pomegranate', 'yogurt', 'cumin'], preparation: ['Mix pomegranate seeds with yogurt and spices.'] },
        { name: 'Vegetable Raita', ingredients: ['yogurt', 'cucumber', 'carrot', 'tomato'], preparation: ['Mix chopped veggies with yogurt and spices.'] },
        { name: 'Dahi Bhalla', ingredients: ['urad dal', 'yogurt', 'spices'], preparation: ['Serve vadas in yogurt topped with spices and chutneys.'] },
        { name: 'Cabbage Salad', ingredients: ['cabbage', 'carrot', 'lemon'], preparation: ['Mix cabbage with carrots and lemon juice.'] },
        { name: 'Green Salad', ingredients: ['lettuce', 'cucumber', 'lemon'], preparation: ['Mix greens with lemon juice.'] },
        { name: 'Sprouted Chana Salad', ingredients: ['sprouted chana', 'onion', 'tomato'], preparation: ['Mix sprouts with vegetables and lemon.'] },
        { name: 'Raw Papaya Salad', ingredients: ['raw papaya', 'tomato', 'chili'], preparation: ['Mix shredded papaya with tomato and spices.'] },
        { name: 'Raita', ingredients: ['yogurt', 'cucumber', 'mint'], preparation: ['Mix yogurt with cucumber and mint.'] }
    ],
    desserts: [
        { name: 'Gulab Jamun', ingredients: ['milk powder', 'sugar', 'rose water'], preparation: ['Shape dough into balls, fry, and soak in syrup.'] },
        { name: 'Rasgulla', ingredients: ['milk', 'sugar', 'water'], preparation: ['Shape chenna into balls, cook in sugar syrup.'] },
        { name: 'Jalebi', ingredients: ['flour', 'sugar', 'saffron'], preparation: ['Pipe flour batter into hot oil and soak in syrup.'] },
        { name: 'Kheer', ingredients: ['milk', 'rice', 'sugar', 'cardamom'], preparation: ['Simmer milk and rice with sugar and cardamom.'] },
        { name: 'Rasmalai', ingredients: ['milk', 'sugar', 'saffron'], preparation: ['Soak chenna discs in sweetened milk.'] },
        { name: 'Ladoo', ingredients: ['gram flour', 'sugar', 'ghee'], preparation: ['Cook flour in ghee, shape with sugar into balls.'] },
        { name: 'Barfi', ingredients: ['milk', 'sugar', 'cardamom'], preparation: ['Cook milk with sugar and cardamom, shape into squares.'] },
        { name: 'Sandesh', ingredients: ['chenna', 'sugar'], preparation: ['Mix chenna with sugar, shape into discs.'] },
        { name: 'Peda', ingredients: ['khoya', 'sugar', 'cardamom'], preparation: ['Cook khoya with sugar, shape into discs.'] },
        { name: 'Halwa', ingredients: ['semolina', 'sugar', 'ghee'], preparation: ['Cook semolina with ghee and sugar.'] },
        { name: 'Badam Kheer', ingredients: ['almonds', 'milk', 'sugar'], preparation: ['Blend almonds, cook with milk and sugar.'] },
        { name: 'Besan Ladoo', ingredients: ['gram flour', 'ghee', 'sugar'], preparation: ['Cook gram flour in ghee, shape with sugar.'] },
        { name: 'Mysore Pak', ingredients: ['gram flour', 'ghee', 'sugar'], preparation: ['Cook flour with sugar and ghee, shape into pieces.'] },
        { name: 'Kaju Katli', ingredients: ['cashew', 'sugar'], preparation: ['Blend cashew with sugar, roll and slice.'] },
        { name: 'Puran Poli', ingredients: ['flour', 'jaggery', 'dal'], preparation: ['Make stuffed flatbreads with dal and jaggery.'] },
        { name: 'Kalakand', ingredients: ['milk', 'sugar'], preparation: ['Cook milk with sugar until thickened.'] },
        { name: 'Rabri', ingredients: ['milk', 'sugar'], preparation: ['Simmer milk until thick, sweeten.'] },
        { name: 'Shrikhand', ingredients: ['yogurt', 'sugar', 'saffron'], preparation: ['Sweeten and flavor yogurt with saffron.'] },
        { name: 'Modak', ingredients: ['rice flour', 'jaggery', 'coconut'], preparation: ['Fill rice dough with sweetened coconut, steam.'] },
        { name: 'Phirni', ingredients: ['rice', 'milk', 'sugar'], preparation: ['Simmer rice with milk and sugar.'] }
    ]
};

